CC=gcc
CFLAGS= -O -D WINDOWS -Wall -std=c99
LDFLAGS= -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lws2_32
EXEC=blokus.exe
SRC=$(wildcard ./src/[^t]*.c)
OBJ=$(SRC:.c=.o)

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	rm -f ./src/*.o core

mrproper: clean
	rm -f $(EXEC)